version: '3.8'

services:
  web-dashboard:
    build:
      context: ./services/web-dashboard
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./services/web-dashboard:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:4000

  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - ./services/backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/county_revenue
      - JWT_SECRET=your_jwt_secret_here
      - PORT=4000
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=county_revenue
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 